#' Pollution Rose Data
#'
#'
#' Requires sample data (as read-in by `import_raw_data()`) and wind data
#' as generated by `wind_data()`.
#'
#' Returns a dataframe with a column of measurements per specified parameter
#' (up to two), a column for wind data, a column for site code, and a column
#' for datetime.
#'
#' Columns are added for year and season, where seasons are:
#' - Winter: 12, 1, 2
#' - Spring: 3, 4, 5
#' - Summer: 6, 7, 8
#' - Fall: 9, 10, 11
#'
#' Generates dataframe to pass to pollutionRoseServer() function in
#' sonomaDashboardUI package...
#'
#' @param sample_data data.frame Sample data data.frame
#' @param wind_data data.frame Wind data as generated by `wind_data()`
#' @param param_code1 string Parameter code to include in dataframe
#' @param duration string Sample duration to filter to, as listed in the
#'                        `sample_duration` column
#' @param param_code2 string (optional) Second parameter code to include in
#'                           dataframe
#'
#' @return data.frame Tidied dataframe with all data needed to create a pollution
#'                    rose.
#' @importFrom magrittr `%>%`
#' @importFrom dplyr group_by summarize ungroup mutate filter select left_join case_when
#' @importFrom lubridate year month
#' @importFrom tidyr spread
#' @export
pollution_rose_data <- function(sample_data,
                                wind_data,
                                param_code1,
                                duration = '1 HOUR',
                                param_code2 = NULL) {
  pr_data <- sample_data %>%
      dplyr::select(aqs_sitecode, parameter, date_local, time_local,
                    sample_duration, sample_measurement,
                    units_of_measure, qualifier)
      dplyr::filter(parameter_code %in% c(param_code1, param_code2),
                    sample_duration == duration) %>%
      dplyr::select(-sample_duration, -qualifier, -units_of_measure) %>%
      dplyr::group_by(aqs_sitecode, parameter, date_local, time_local) %>%
      dplyr::summarize(sample_measurement = mean(sample_measurement,
                                                 na.rm = TRUE)) %>%
      dplyr::ungroup() %>%
      tidyr::spread(parameter, sample_measurement) %>%
      dplyr::left_join(wind_data) %>%
      dplyr::filter(!is.na(WD), !is.na(WS))

    pr_data <- pr_data %>%
      dplyr::mutate(date_time_chr = paste(date_local, time_local)) %>%
      dplyr::mutate(date_time = as.POSIXct(date_time_chr,
                                    format = '%Y-%m-%d %H:%M', tz = '')) %>%
      dplyr::select(-date_local, -time_local, -date_time_chr) %>%
      dplyr::mutate(year = lubridate::year(date_time),
                    month = lubridate::month(date_time)) %>%
      dplyr::mutate(season = dplyr::case_when(
        month < 3 ~ 'Winter',
        month < 6 ~ 'Spring',
        month < 9 ~ 'Summer',
        month < 12 ~ 'Fall',
        month == 12 ~ 'Winter',
        TRUE ~ 'Missing'
      ))

    return(pr_data)
}
