#' Generate time series dataframe
#'
#' Requires raw data (data) and detection limits summary data, generated
#' with the `detection_limit_data()` function.
#'
#' Returns a tidied dataframe with time series data for all non-wind parameters.
#'
#' @param sample_data data.frame sampleData data.frame
#' @param method_mdl_summary Detection limit summary data as generated by the
#'                             `method_mdl_summary()` function.
#' @param duration string The sample duration to include in the dataframe as it
#'                        appears in the sample_duration column (e.g.
#'                        '1 HOUR', '24-HOUR').
#'
#' @return data.frame Tidied dataframe with measurement data for the specified
#'                    duration per date-time value across parameters.
#' @importFrom magrittr `%>%`
#' @importFrom dplyr select filter distinct left_join
#' @export
#'
#' @examples
#' method_mdl_summary <- method_mdl_summary(sample_data)
#' ts_1hr_data <- ts_data(sample_data, method_mdl_summary, duration = '1 HOUR')
ts_data <- function(sample_data,
                    method_mdl_summary,
                    duration) {

  winds <- c('61101', '61102','61103', '61104')

  GTDL_species <- method_mdl_summary %>%
    dplyr::filter(pctGTDL >= 25) %>%
    dplyr::select(parameter, method, method_code) %>%
    dplyr::distinct()

  data_i <- GTDL_species %>%
    dplyr::left_join(sample_data) %>%
    dplyr::select(aqs_sitecode, parameter_code,  parameter, method_code, poc,
           date_local, time_local, sample_measurement, units_of_measure,
           sample_duration,
           qualifier, method)
  #browser()
  ts_data <- data_i %>%
    dplyr::filter(sample_duration == duration) %>%
    dplyr::filter(!(parameter_code %in% winds)) %>%
    dplyr::mutate(date_time_chr = paste(date_local, time_local))%>%
    dplyr::mutate(date_time = as.POSIXct(date_time_chr,
                                  format = "%Y-%m-%d %H:%M",
                                  tz = '')) %>%
    dplyr::select(-date_local, -time_local,
           -method_code, -qualifier, -date_time_chr) %>%
    dplyr::filter(!is.na(sample_measurement),
                  !is.na(date_time))

  return(ts_data)

}
