#' TS parameters
#'
#' Create data frame listing unique parameters per site from a
#' time series dataframe (generated by `ts_data()`).
#'
#' @param ts_data data.frame Time series data generated by `ts_data()`
#'
#' @return data.frame List of sites and parameters in a time series dataframe
#' @importFrom magrittr `%>%`
#' @importFrom dplyr select group_by_all summarize ungroup n
#' @export
#'
#' @examples
#' method_mdl_summary <- method_mdl_summary(sample_data)
#' ts_1hr_data <- ts_data(sample_data, method_mdl_summary, duration = '1 HOUR')
#' ts_parameters(ts_1hr_data)
ts_parameters <- function(ts_data) {
  parameters <- ts_data %>%
    dplyr::select(aqs_sitecode, parameter, parameter_code) %>%
    dplyr::group_by_all() %>%
    dplyr::summarize(count = dplyr::n()) %>%
    dplyr::ungroup()
  
  return(parameters)
}
